const METRICS = {
  oqim: { id: 'oqim', pillar: 'ravonlik', title: 'Ravon oqim' },
  tezlik: { id: 'tezlik', pillar: 'ravonlik', title: 'Mos nutq tezligi' },
  sozTanlash: { id: 'sozTanlash', pillar: 'aniqlik', title: 'Aniq so‘z tanlovi' },
  parazit: { id: 'parazit', pillar: 'aniqlik', title: 'Parazit so‘zlar nazorati' },
  mantiq: { id: 'mantiq', pillar: 'tuzilma', title: 'Mantiqiy ketma-ketlik' },
  dalil: { id: 'dalil', pillar: 'tuzilma', title: 'Misol va dalil' },
  talaffuz: { id: 'talaffuz', pillar: 'yetkazish', title: 'Aniq talaffuz' },
  ovoz: { id: 'ovoz', pillar: 'yetkazish', title: 'Ovoz, nafas va intonatsiya' },
  qatiyat: { id: 'qatiyat', pillar: 'ishonch', title: 'Vokal ishonch va qat’iyat' },
  tasir: { id: 'tasir', pillar: 'ishonch', title: 'Tushunarlilik va ta’sir' }
};

const PILLARS = [
  { id: 'ravonlik', title: 'Ravonlik', metricIds: ['oqim', 'tezlik'] },
  { id: 'aniqlik', title: 'Aniqlik', metricIds: ['sozTanlash', 'parazit'] },
  { id: 'tuzilma', title: 'Tuzilma', metricIds: ['mantiq', 'dalil'] },
  { id: 'yetkazish', title: 'Yetkazish', metricIds: ['talaffuz', 'ovoz'] },
  { id: 'ishonch', title: 'Ishonch', metricIds: ['qatiyat', 'tasir'] }
];

const STAGES = [
  { id: 1, from: 1, to: 7, title: 'O‘zingni kuzat', description: 'Ovoz, nafas va odatlarni xolis ko‘rish' },
  { id: 2, from: 8, to: 14, title: 'Fikrni tuz', description: 'Fikrni ravon va mantiqiy yetkazish' },
  { id: 3, from: 15, to: 21, title: 'Ishonchni oshir', description: 'Ohang, hikoya va tinglovchiga moslashish' },
  { id: 4, from: 22, to: 29, title: 'Real vaziyatda sina', description: 'Intervyu, yig‘ilish va spontan javoblar' },
  { id: 5, from: 30, to: 30, title: 'Natijani isbotla', description: '1-kun va 30-kunni solishtirish' }
];

const COMMON_FOCUS = [
  'Jim pauza qilaman',
  'Bitta aniq fikr bilan boshlayman',
  'Bitta hayotiy misol qo‘shaman',
  '10% sekinroq gapiraman',
  'So‘z oxirlarini aniq aytaman',
  'Xulosani bitta jumlada tugataman'
];

const DAYS = [
  {
    day: 1,
    title: 'Boshlang‘ich audio',
    skill: 'Hozirgi nutqingizni xolis belgilash',
    durationMinutes: 15,
    recommendedSeconds: 60,
    activeMetricIds: Object.keys(METRICS),
    warmup: 'Yelkalarni bo‘shating. Burundan 4 soniya nafas oling, 2 soniya ushlab, 6 soniyada chiqaring. Uch marta takrorlang.',
    prompt: 'O‘zingizni tanishtiring: nima bilan shug‘ullanasiz, nimaga qiziqasiz va nutqingizda nimani yaxshilamoqchisiz?',
    keywords: ['Men haqimda', 'Qiziqishim', 'Maqsadim'],
    what: 'Bu yozuv sizning boshlang‘ich nuqtangiz. Hozir mukammal gapirish shart emas; tabiiy holatingizni saqlash muhim.',
    why: '30-kunda aynan shu mavzuni takrorlaysiz. Natija xotiraga emas, ikki real yozuvga tayangan holda ko‘rinadi.',
    how: ['Telefonni og‘izdan 30–40 sm uzoqda tuting.', 'Uch tayanch so‘zni ko‘rib, matnsiz gapiring.', 'Xato qilsangiz to‘xtamay davom eting.'],
    goodExample: '“Men Diyorbekman. Dizayn bilan shug‘ullanaman. Nutqimda fikrni qisqa va aniq tugatishni o‘rganmoqchiman.”',
    badExample: 'Oldindan yozilgan uzun matnni tez o‘qish yoki o‘zingizni ataylab boshqacha ko‘rsatish.',
    check: 'Yozuv tabiiy chiqdimi va uch asosiy fikr tugallandimi?'
  },
  {
    day: 2,
    title: 'Nafas va holat',
    skill: 'Gap oxirigacha nafasni yetkazish',
    durationMinutes: 12,
    recommendedSeconds: 60,
    activeMetricIds: ['tezlik', 'talaffuz', 'ovoz'],
    warmup: 'Tik o‘tiring. Kaftni qoringa qo‘yib, 4 soniyada nafas oling va “ssss” tovushi bilan 8 soniyada chiqaring.',
    prompt: 'Odatiy kuningiz ertalabdan kechgacha qanday o‘tishini aytib bering.',
    keywords: ['Ertalab', 'Asosiy ish', 'Kechqurun'],
    what: 'Nafas — gapning yonilg‘isi. Yelka bilan qisqa nafas olish jumla oxirini yutib yuboradi.',
    why: 'Barqaror nafas tezlikni boshqaradi, ovozni aniqroq va ishonchliroq qiladi.',
    how: ['Har yangi fikrdan oldin sokin nafas oling.', 'Bitta nafasga bitta tugallangan jumla ayting.', 'Jumla oxirini ovozsiz qoldirmang.'],
    goodExample: 'Har bir fikrdan keyin yarim soniya to‘xtab, keyingi jumlani yangi nafas bilan boshlash.',
    badExample: 'Bir nafasda juda ko‘p gap aytib, oxirgi so‘zlarni shivirlab yuborish.',
    check: 'Jumlalarning oxiri ham boshidagi kabi aniq eshitildimi?'
  },
  {
    day: 3,
    title: 'Aniq talaffuz',
    skill: 'So‘z boshini va oxirini ravshan aytish',
    durationMinutes: 12,
    recommendedSeconds: 70,
    activeMetricIds: ['talaffuz', 'tezlik', 'tasir'],
    warmup: 'Lablarni 10 soniya titrating. So‘ng “ra–la–sa–sha–cha–qa–g‘a–xa–o‘” bo‘g‘inlarini sekin ayting.',
    prompt: 'Sizga foyda bergan bir odatni tushuntiring va uni qanday boshlaganingizni ayting.',
    keywords: ['Odat', 'Boshlanish', 'Natija'],
    what: 'Aniq talaffuz baland gapirish emas. Har bir muhim bo‘g‘in va so‘z oxirini eshitiladigan qilishdir.',
    why: 'Tinglovchi so‘zlarni taxmin qilib o‘tirmasa, mazmunga ko‘proq e’tibor beradi.',
    how: ['Avval qiyin so‘zlarni alohida sekin ayting.', 'Tezlikni biroz pasaytiring.', 'Gap oxiridagi undoshlarni yutib yubormang.'],
    goodExample: '“Tartib-intizom natijani barqaror qiladi” jumlasini har bir so‘z oxiri bilan aytish.',
    badExample: 'Tezlik uchun bo‘g‘inlarni qo‘shib yuborish va ovozni gap oxirida pasaytirib yuborish.',
    check: 'Qayta eshitganda biror so‘zni taxmin qilishga to‘g‘ri keldimi?'
  },
  {
    day: 4,
    title: 'Jim pauza',
    skill: '“Eee” o‘rniga mazmunli jimlik ishlatish',
    durationMinutes: 12,
    recommendedSeconds: 60,
    activeMetricIds: ['oqim', 'parazit', 'qatiyat'],
    warmup: 'Uchta sodda jumla ayting. Har jumla orasida ataylab bir soniya jim turing.',
    prompt: 'So‘nggi paytda o‘rgangan foydali narsangizni tushuntiring.',
    keywords: ['Nima', 'Qanday', 'Foydasi'],
    what: 'Jim pauza xato emas. U sizga keyingi fikrni tanlash, tinglovchiga esa oldingi fikrni qabul qilish vaqtini beradi.',
    why: '“Eee”, “haligi”, “demak” kabi avtomatik so‘zlar kamayganda nutq toza va qat’iy eshitiladi.',
    how: ['Parazit kelayotganini sezsangiz labni yoping.', 'Bir marta sokin nafas oling.', 'Keyingi aniq jumla bilan davom eting.'],
    goodExample: '“Buning asosiy sababi... [jim pauza] vaqtni tejashidir.”',
    badExample: 'Har bo‘shliqni “eee” yoki “anaqa” bilan to‘ldirish.',
    check: 'Parazitlar soni kamayib, jim pauzalar tabiiy chiqdimi?'
  },
  {
    day: 5,
    title: 'So‘z aniqligi',
    skill: 'Umumiy so‘z o‘rniga ko‘rinadigan belgi aytish',
    durationMinutes: 10,
    recommendedSeconds: 75,
    activeMetricIds: ['sozTanlash', 'dalil', 'tasir'],
    warmup: 'Yon atrofingizdagi buyumni “yaxshi”, “juda” va “narsa” so‘zlarisiz uchta belgi bilan tariflang.',
    prompt: 'Har kuni ishlatadigan bitta buyum yoki ilovani beshta aniq belgi bilan tariflang.',
    keywords: ['Ko‘rinishi', 'Vazifasi', 'Foydasi'],
    what: 'Aniq so‘z tinglovchining ko‘z oldida tasvir hosil qiladi. Umumiy baho esa kam ma’lumot beradi.',
    why: 'Aniq detal nutqni qisqartiradi va fikrni esda qolarli qiladi.',
    how: ['“Qanday?” degan savolni bering.', 'Son, joy, rang, vaqt yoki harakat qo‘shing.', 'Keraksiz kuchaytiruvchi so‘zlarni olib tashlang.'],
    goodExample: '“Telefon qulay” o‘rniga “telefon bir quvvatda ikki kun ishlaydi”.',
    badExample: '“Bu juda yaxshi, zo‘r va foydali narsa” deb aniq dalilsiz baholash.',
    check: 'Tinglovchi ta’rifdan buyumni ko‘z oldiga keltira oladimi?'
  },
  {
    day: 6,
    title: 'Spontan javob',
    skill: 'Besh soniyada fikrni boshlab, tugatish',
    durationMinutes: 12,
    recommendedSeconds: 60,
    activeMetricIds: ['oqim', 'mantiq', 'qatiyat'],
    warmup: '“Menimcha... Chunki... Masalan... Shuning uchun...” qolipini bir marta ovoz chiqarib ayting.',
    prompt: 'Masofadan ishlash samaraliroqmi yoki ofisda ishlashmi? O‘z fikringizni ayting.',
    keywords: ['Fikrim', 'Sabab', 'Xulosa'],
    what: 'Spontan javob darhol mukammal javob berish emas. Bir asosiy pozitsiyani tez tanlab, uni tugatishdir.',
    why: 'Intervyu va yig‘ilishda uzoq kirishdan ko‘ra aniq birinchi jumla ishonch beradi.',
    how: ['Besh soniyada bitta pozitsiya tanlang.', 'Bitta sabab va bitta misol ayting.', 'Xulosada savolga to‘g‘ridan-to‘g‘ri javob bering.'],
    goodExample: '“Men uchun ofis samaraliroq, chunki tez muhokama qilish oson. Masalan... Shuning uchun...”',
    badExample: 'Savolni bir necha marta takrorlab, pozitsiyani oxirigacha aytmaslik.',
    check: 'Birinchi o‘n soniyada asosiy javob eshitildimi?'
  },
  {
    day: 7,
    title: 'Birinchi taqqoslash',
    skill: '1-kundagi nutqni ongli ravishda yaxshilash',
    durationMinutes: 18,
    recommendedSeconds: 60,
    activeMetricIds: Object.keys(METRICS),
    warmup: '1-kundagi asosiy mavzuni eslang. Uch tayanch so‘zni yozing va bir marta chuqur nafas oling.',
    prompt: 'O‘zingizni tanishtiring: nima bilan shug‘ullanasiz, nimaga qiziqasiz va nutqingizda nimani yaxshilamoqchisiz?',
    keywords: ['Men haqimda', 'Qiziqishim', 'Maqsadim'],
    what: 'Bu nazorat kuni. Maqsad katta ball emas, 1-kun bilan bir xil vazifada kuzatiladigan farqni topish.',
    why: 'Bir xil mavzu va vaqt sharoiti o‘zgarishni adolatliroq ko‘rsatadi.',
    how: ['1-kundagi yozuvni bir marta eshiting.', 'Faqat bitta kuchli va bitta zaif nuqtani yozing.', 'Yangi yozuvda shu bitta zaiflikka e’tibor bering.'],
    goodExample: '“Bu safar gap oxirlarini aniq aytaman” kabi o‘lchanadigan fokus tanlash.',
    badExample: 'Barcha kamchilikni birdan tuzatishga urinish.',
    check: 'Qaysi bitta ko‘rsatkichda real farq eshitildi?'
  },
  {
    day: 8,
    title: 'Nima, nega, qanday',
    skill: 'Murakkab fikrni sodda tushuntirish',
    durationMinutes: 15,
    recommendedSeconds: 90,
    activeMetricIds: ['mantiq', 'sozTanlash', 'tasir', 'dalil'],
    warmup: '“Telefon — aloqa vositasi. U masofani qisqartiradi. Qo‘ng‘iroq va xabar orqali ishlaydi” misolini ovoz chiqarib ayting.',
    prompt: 'Bulutli saqlash nima, nega kerak va qanday ishlaydi?',
    keywords: ['Nima', 'Nega', 'Qanday'],
    what: 'NNQ modeli fikrni uch qismga bo‘ladi: tushuncha, qiymat va ishlash usuli.',
    why: 'Tinglovchi avval mavzuni tushunadi, keyin foydasini ko‘radi va oxirida amaliy tasavvur oladi.',
    how: ['15 soniyada “Nima?”ga javob bering.', '30 soniyada “Nega kerak?”ni ayting.', '30–40 soniyada “Qanday?”ni misol bilan tushuntiring.'],
    goodExample: '“Bulutli saqlash — internetdagi shaxsiy ombor. Telefon yo‘qolsa ham fayl saqlanadi. Hisobga kirib istalgan qurilmadan ochasiz.”',
    badExample: 'Texnik jargon bilan boshlab, foydalanuvchiga nima berishini aytmaslik.',
    check: 'Nima, nega va qanday qismlarini alohida eshitish mumkinmi?'
  },
  {
    day: 9,
    title: 'Fikr, sabab, misol, xulosa',
    skill: 'Pozitsiyani to‘rt qadamda asoslash',
    durationMinutes: 15,
    recommendedSeconds: 90,
    activeMetricIds: ['mantiq', 'dalil', 'qatiyat', 'tasir'],
    warmup: '“Menimcha... Sababi... Masalan... Xulosa qilib...” iboralarini bir marta ayting.',
    prompt: 'Har kuni kitob o‘qish foydalimi? Pozitsiyangizni FSMX tartibida ayting.',
    keywords: ['Fikr', 'Sabab', 'Misol'],
    what: 'FSMX yoki PREP modeli fikrni pozitsiya, sabab, misol va qayta xulosa orqali mustahkamlaydi.',
    why: 'Sababsiz fikr da’vo bo‘lib qoladi; misol esa sababni ko‘rinadigan qiladi.',
    how: ['Pozitsiyani birinchi jumlada ayting.', 'Eng kuchli bitta sababni tanlang.', 'Qisqa misol va yakuniy xulosa qo‘shing.'],
    goodExample: '“Har kuni o‘qish foydali. Chunki fikr uchun yangi material beradi. Masalan... Shuning uchun kuniga o‘n sahifa yetarli.”',
    badExample: 'Uchta sababni boshlab, hech birini misol bilan tugatmaslik.',
    check: 'Xulosa boshidagi fikrga qaytdimi?'
  },
  {
    day: 10,
    title: 'Muammo, sabab, yechim',
    skill: 'Muammoni shikoyatsiz tushuntirish',
    durationMinutes: 15,
    recommendedSeconds: 90,
    activeMetricIds: ['mantiq', 'dalil', 'sozTanlash'],
    warmup: 'Bitta kundalik muammoni bir jumlada, hissiy bahosiz ayting.',
    prompt: 'Kundalik vaqtingiz yetishmasligi muammosini sabab va amaliy yechim bilan tushuntiring.',
    keywords: ['Muammo', 'Sabab', 'Yechim'],
    what: 'MSY modeli muammoni ayblovdan ajratadi va nutqni harakat bilan yakunlaydi.',
    why: 'Rahbar, sherik yoki mijoz bilan suhbatda aniq sabab va yechim konstruktiv eshitiladi.',
    how: ['Muammoni kuzatiladigan holat bilan ayting.', 'Eng muhim bitta sababni ko‘rsating.', 'Kim, qachon va nima qilishini aytgan yechim bering.'],
    goodExample: '“Topshiriqlar kechikyapti. Sababi ustuvorliklar yozilmagan. Har tong uchta asosiy vazifani belgilaymiz.”',
    badExample: '“Hammasi yomon, vaqt umuman yetmaydi” deb sabab va yechimsiz shikoyat qilish.',
    check: 'Yechimni ertaga amalda boshlash mumkinmi?'
  },
  {
    day: 11,
    title: 'Vaziyat, harakat, natija',
    skill: 'Shaxsiy tajribani dalilga aylantirish',
    durationMinutes: 15,
    recommendedSeconds: 110,
    activeMetricIds: ['mantiq', 'dalil', 'tasir'],
    warmup: 'Kecha qilgan bitta ishingizni “vaziyat–harakat–natija” uch jumlasida ayting.',
    prompt: 'Bir muammoni muvaffaqiyatli hal qilgan vaziyatingizni VHN yoki STAR modeli bilan ayting.',
    keywords: ['Vaziyat', 'Harakat', 'Natija'],
    what: 'VHN modeli voqeani fonda yo‘qotib qo‘ymay, siz qilgan harakat va natijaga olib keladi.',
    why: 'Intervyuda “men yaxshi ishlayman”dan ko‘ra real vaziyat va natija kuchli dalildir.',
    how: ['Vaziyatni ikki jumlada cheklang.', 'Aynan siz qilgan harakatni ayting.', 'Natijani o‘lchov yoki aniq o‘zgarish bilan tugating.'],
    goodExample: '“Muddat qisqa edi. Men vazifani uch bosqichga ajratdim. Natijada ishni bir kun oldin tugatdik.”',
    badExample: 'Vaziyat haqida uzoq gapirib, o‘zingiz nima qilganingizni aytmaslik.',
    check: 'Tinglovchi sizning hissangizni aniq tushundimi?'
  },
  {
    day: 12,
    title: 'Fikrlarni bog‘lash',
    skill: 'Nutqni tabiiy ko‘priklar bilan davom ettirish',
    durationMinutes: 12,
    recommendedSeconds: 90,
    activeMetricIds: ['oqim', 'mantiq', 'sozTanlash'],
    warmup: '“Avvalo, masalan, biroq, shuning uchun, xulosa qilib” iboralarini turli ohangda ayting.',
    prompt: 'Telefonning foydali va zararli tomonlarini muvozanatli tushuntiring.',
    keywords: ['Avvalo', 'Biroq', 'Shuning uchun'],
    what: 'O‘tish iboralari tinglovchiga fikrlar o‘rtasidagi munosabatni ko‘rsatadi.',
    why: 'Bog‘lovchisiz gaplar alohida bo‘lakdek eshitiladi; ortiqcha bog‘lovchi esa sun’iylik yaratadi.',
    how: ['Yangi nuqtada “avvalo” yoki “yana bir jihat” deng.', 'Qarama-qarshilikda “biroq”dan foydalaning.', 'Natijani “shuning uchun” bilan bog‘lang.'],
    goodExample: '“Avvalo, telefon aloqani tezlashtiradi. Biroq nazoratsiz foydalanish diqqatni bo‘ladi. Shuning uchun vaqt chegarasi kerak.”',
    badExample: 'Har jumlani “demak” bilan boshlash.',
    check: 'Har bog‘lovchi mazmunga xizmat qildimi?'
  },
  {
    day: 13,
    title: 'So‘z topilmaganda',
    skill: 'To‘xtamasdan qayta ifodalash',
    durationMinutes: 12,
    recommendedSeconds: 80,
    activeMetricIds: ['oqim', 'sozTanlash', 'qatiyat'],
    warmup: '“Termos” so‘zini ishlatmasdan uning vazifasi va ko‘rinishini tariflang.',
    prompt: '“Sun’iy intellekt” atamasini ishlatmasdan, uni oddiy odamga tushuntiring.',
    keywords: ['Vazifasi', 'Misol', 'O‘xshatish'],
    what: 'Kerakli so‘z kelmasa, belgi, vazifa, o‘xshatish yoki misol bilan davom etish mumkin.',
    why: 'Ravonlik barcha so‘zni bilish emas; fikrni boshqa yo‘l bilan yetkazish qobiliyatidir.',
    how: ['“Bu — ... qiladigan vosita” deb vazifani ayting.', 'Oddiy hayotiy misol bering.', 'Keyin topilgan aniq so‘zni qo‘shing.'],
    goodExample: '“Bu katta hajmdagi ma’lumotdan naqsh topib, savolga javob beradigan dastur.”',
    badExample: 'So‘zni eslash uchun o‘n soniya jim qolish yoki gapni butunlay tashlab ketish.',
    check: 'So‘zsiz ham tushuncha tinglovchiga yetdimi?'
  },
  {
    day: 14,
    title: 'Qisqa 4/3/2',
    skill: 'Mazmunni yo‘qotmasdan ixchamlashtirish',
    durationMinutes: 18,
    recommendedSeconds: 120,
    activeMetricIds: ['oqim', 'tezlik', 'mantiq', 'tasir'],
    warmup: 'Bitta voqeani avval uch jumlada, keyin bitta jumlada ayting.',
    prompt: 'Kelajakda egallamoqchi bo‘lgan ko‘nikmangizni tushuntiring.',
    keywords: ['Maqsad', 'Reja', 'Natija'],
    what: '4/3/2 mashqi bir mazmunni takrorlab, har safar vaqtni qisqartiradi. Bugun yengil variant: 2 daqiqa va 90 soniya.',
    why: 'Takrorlash fikrni avtomatlashtiradi, qisqartirish esa ortiqcha jumlalarni ko‘rsatadi.',
    how: ['Birinchi urinishda to‘liq mazmunni ayting.', 'Eng muhim uch nuqtani ajrating.', 'Ikkinchi urinishda shu nuqtalarni ixchamroq ayting.'],
    goodExample: 'Ikkinchi urinishda misolni saqlab, takrorlangan kirishni qisqartirish.',
    badExample: 'Vaqtga sig‘ish uchun tushunarsiz darajada tezlashish.',
    check: 'Ikkinchi urinish qisqaroq, lekin baribir tushunarlimi?'
  },
  {
    day: 15,
    title: 'Oraliq sinov',
    skill: 'Ikki haftalik ko‘nikmalarni birlashtirish',
    durationMinutes: 20,
    recommendedSeconds: 120,
    activeMetricIds: Object.keys(METRICS),
    warmup: 'Nafas, talaffuz va uch tayanch so‘z mashqini ketma-ket bajaring.',
    prompt: 'Ish yoki o‘qishdagi bir muammoni tushuntiring va amaliy yechim taklif qiling.',
    keywords: ['Muammo', 'Dalil', 'Yechim'],
    what: 'Bu nazorat yozuvi. Tuzilma, aniqlik va yetkazish birgalikda tekshiriladi.',
    why: 'Alohida mashqlar real nutqda bir vaqtda ishlay olishi muhim.',
    how: ['Muammoni birinchi 20 soniyada ayting.', 'Sababni misol bilan oching.', 'Aniq yechim va xulosa bilan tugating.'],
    goodExample: 'Muammo → kuzatilgan dalil → sabab → bajariladigan yechim.',
    badExample: 'Ko‘p maslahat berib, asosiy muammoni aniq nomlamaslik.',
    check: 'Tinglovchi muammo va keyingi qadamni bitta eshitishda tushunadimi?'
  },
  {
    day: 16,
    title: 'Oldin, burilish, keyin',
    skill: 'Voqeani qiziqarli hikoyaga aylantirish',
    durationMinutes: 15,
    recommendedSeconds: 110,
    activeMetricIds: ['mantiq', 'dalil', 'ovoz', 'tasir'],
    warmup: '“Avval... Ammo bir kuni... Shundan keyin...” qolipida uch jumla ayting.',
    prompt: 'Fikringizni o‘zgartirgan bir voqeani hikoya qiling.',
    keywords: ['Oldin', 'Burilish', 'Keyin'],
    what: 'Hikoyada burilish nuqtasi voqeani oddiy ro‘yxatdan mazmunli o‘zgarishga aylantiradi.',
    why: 'Odamlar quruq maslahatdan ko‘ra o‘zgarish jarayonini yaxshi eslab qoladi.',
    how: ['Oldingi holatni qisqa ko‘rsating.', 'O‘zgarishga sabab bo‘lgan lahzani ayting.', 'Keyingi natija va xulosani bering.'],
    goodExample: '“Oldin savol berishga tortinardim. Bir kuni noto‘g‘ri tushunib katta xato qildim. Shundan keyin aniqlashtirishni odat qildim.”',
    badExample: 'Voqealarni vaqt tartibida sanab, burilish va xulosani ajratmaslik.',
    check: 'Hikoyadagi o‘zgarish lahzasi aniq eshitildimi?'
  },
  {
    day: 17,
    title: 'Auditoriyaga moslashish',
    skill: 'Bir fikrni turli odamga turlicha aytish',
    durationMinutes: 18,
    recommendedSeconds: 100,
    activeMetricIds: ['sozTanlash', 'dalil', 'tasir'],
    warmup: '“Internet xavfsizligi”ni avval bolaga, keyin mutaxassisga bitta jumlada tushuntiring.',
    prompt: 'Jamg‘arma qilish nega kerakligini yosh o‘quvchi va ishchi mutaxassisga moslab tushuntiring.',
    keywords: ['Kimga', 'Qaysi misol', 'Qaysi ohang'],
    what: 'Yaxshi nutq faqat to‘g‘ri mazmun emas; tinglovchining tajribasiga mos so‘z va misoldir.',
    why: 'Bir xil jargon va bir xil ohang barcha auditoriyada ishlamaydi.',
    how: ['Tinglovchining nimani bilishini taxmin qiling.', 'Unga tanish misol tanlang.', 'Mazmunni saqlab, so‘z va ohangni o‘zgartiring.'],
    goodExample: 'O‘quvchiga cho‘ntak puli, mutaxassisga favqulodda jamg‘arma misolini berish.',
    badExample: 'Bolaga moliyaviy terminlar bilan yoki mutaxassisga haddan ortiq sodda gapirish.',
    check: 'Ikki variantning misoli va tili aniq farq qildimi?'
  },
  {
    day: 18,
    title: 'Ovoz bilan aloqa',
    skill: 'Faqat audio orqali tinglovchini jalb qilish',
    durationMinutes: 12,
    recommendedSeconds: 80,
    activeMetricIds: ['ovoz', 'qatiyat', 'tasir'],
    warmup: 'Bir jumlani xotirjam, qiziqqan va qat’iy ohangda uch marta ayting.',
    prompt: 'Siz qadrlaydigan bir tamoyilni tinglovchiga bevosita murojaat qilib tushuntiring.',
    keywords: ['Murojaat', 'Urg‘u', 'Xulosa'],
    what: 'Audio nutqda yuz ifodasi ko‘rinmaydi. Qiziqish, ishonch va urg‘u ovoz orqali yetadi.',
    why: 'Bir xil ohang mazmunni tekis qiladi; haddan ortiq dramatik ohang esa sun’iy eshitiladi.',
    how: ['Muhim so‘zdan oldin qisqa pauza qiling.', 'Muhim so‘zni biroz aniqroq ayting.', 'Xulosada ovozni shoshmasdan tugating.'],
    goodExample: '“Siz bugun bitta narsani sinab ko‘rishingiz mumkin: ...” deb tinglovchiga murojaat qilish.',
    badExample: 'Butun nutqni bir xil tezlik va balandlikda aytish.',
    check: 'Muhim joylar faqat eshitish orqali ham ajralib turdimi?'
  },
  {
    day: 19,
    title: 'Mazmunni qayta aytish',
    skill: 'Asosiy fikrni o‘z so‘zingiz bilan saqlash',
    durationMinutes: 15,
    recommendedSeconds: 120,
    activeMetricIds: ['mantiq', 'sozTanlash', 'oqim'],
    warmup: 'Bugun o‘qigan bir xabarni ikki jumlada o‘z so‘zingiz bilan ayting.',
    prompt: 'Yaqinda ko‘rgan yoki o‘qigan foydali materialning asosiy g‘oyasini qayta ayting.',
    keywords: ['Asosiy g‘oya', 'Ikki dalil', 'Xulosa'],
    what: 'Qayta aytish matnni yoddan takrorlash emas. Asosiy g‘oya va kerakli dalillarni yangi, sodda shaklda yetkazishdir.',
    why: 'Bu ko‘nikma o‘qish, uchrashuv va taqdimotlarda mazmunni tez anglashga yordam beradi.',
    how: ['Bitta asosiy g‘oyani tanlang.', 'Uni qo‘llovchi ikki muhim tafsilotni ayting.', 'Muallif fikri va o‘z fikringizni ajrating.'],
    goodExample: '“Materialning asosiy g‘oyasi shuki... Muallif bunga ikki sabab beradi...”',
    badExample: 'Har bir detalni ketma-ket aytib, asosiy fikrni yo‘qotish.',
    check: 'Manbani ko‘rmagan odam asosiy mazmunni tushunadimi?'
  },
  {
    day: 20,
    title: 'Muloyim e’tiroz',
    skill: 'Qarshi fikrni hurmat bilan asoslash',
    durationMinutes: 15,
    recommendedSeconds: 90,
    activeMetricIds: ['qatiyat', 'dalil', 'ovoz', 'tasir'],
    warmup: '“Bu fikrning bir qismiga qo‘shilaman, shu bilan birga...” jumlasini xotirjam ayting.',
    prompt: '“Muvaffaqiyat uchun faqat iste’dod yetarli” fikriga muloyim e’tiroz bildiring.',
    keywords: ['Tan olish', 'Farqli fikr', 'Dalil'],
    what: 'Muloyim e’tiroz avval suhbatdoshning mantiqli qismini tan oladi, keyin farqli fikrni dalil bilan beradi.',
    why: 'Keskin “yo‘q” himoya reaksiyasini uyg‘otadi; hurmatli e’tiroz esa suhbatni davom ettiradi.',
    how: ['Umumiy nuqtani tan oling.', 'Farqli fikringizni aniq ayting.', 'Bitta sabab yoki misol bilan asoslang.'],
    goodExample: '“Iste’dod boshlashga yordam beradi, bunga qo‘shilaman. Shu bilan birga, barqaror mashq natijani belgilaydi...”',
    badExample: '“Bu umuman noto‘g‘ri” deb odamning o‘ziga baho berish.',
    check: 'E’tiroz qat’iy, lekin hurmatli eshitildimi?'
  },
  {
    day: 21,
    title: 'Ikkinchi taqqoslash',
    skill: 'Uzoqroq nutqda ravonlikni saqlash',
    durationMinutes: 20,
    recommendedSeconds: 120,
    activeMetricIds: Object.keys(METRICS),
    warmup: '14-kundagi uch tayanch so‘zni eslang va bir daqiqalik qisqa reja tuzing.',
    prompt: 'Kelajakda egallamoqchi bo‘lgan ko‘nikmangizni va unga erishish rejangizni tushuntiring.',
    keywords: ['Maqsad', 'Bosqichlar', 'Natija'],
    what: 'Bu nazorat kuni 14-kundagi mavzuni qayta bajarib, tuzilma va ravonlikni solishtiradi.',
    why: 'Bir hafta ichidagi o‘zgarish aynan bir xil vazifada aniqroq eshitiladi.',
    how: ['Asosiy fikrni boshida ayting.', 'Uchta bosqichdan oshirmang.', 'Xulosada birinchi amaliy qadamni ayting.'],
    goodExample: 'Maqsad → uch bosqich → birinchi qadam tartibi.',
    badExample: 'Ko‘p reja aytib, qachon boshlashni ko‘rsatmaslik.',
    check: '14-kunga qaraganda tuzilma va tezlik barqarorroqmi?'
  },
  {
    day: 22,
    title: '10 soniyalik reja',
    skill: 'Qisqa tayyorgarlik bilan spontan gapirish',
    durationMinutes: 12,
    recommendedSeconds: 90,
    activeMetricIds: ['oqim', 'mantiq', 'qatiyat'],
    warmup: 'Tasodifiy mavzu tanlab, o‘n soniyada kirish–asos–xulosa uchun uch so‘z yozing.',
    prompt: 'Shahar hayotining bitta afzalligi va bitta qiyinchiligini tushuntiring.',
    keywords: ['Afzallik', 'Qiyinchilik', 'Xulosa'],
    what: 'Tez reja to‘liq matn emas. U nutq yo‘nalishini saqlaydigan uchta tayanch nuqtadir.',
    why: 'Rejasiz spontan nutq takrorlanadi; uzun reja esa tabiiylikni yo‘qotadi.',
    how: ['O‘n soniyada uch tayanch so‘z tanlang.', 'Har biriga bittadan asosiy jumla ayting.', 'Oxirida muvozanatli xulosa bering.'],
    goodExample: '“Imkoniyat — shovqin — tanlov” kabi uch qisqa tayanch.',
    badExample: 'Tayyorgarlik vaqtida to‘liq jumlalar yozish.',
    check: 'Nutq uch tayanch bo‘ylab izchil bordimi?'
  },
  {
    day: 23,
    title: 'Uchta kalit so‘z',
    skill: 'Matnga qaramasdan gapirish',
    durationMinutes: 12,
    recommendedSeconds: 90,
    activeMetricIds: ['oqim', 'qatiyat', 'tasir'],
    warmup: 'Bir mavzu uchun faqat uchta ot yozing; fe’l va tayyor jumla yozmang.',
    prompt: 'Siz uchun yaxshi dam olish kuni qanday o‘tishini uchta kalit so‘z bilan ayting.',
    keywords: ['Joy', 'Faoliyat', 'His'],
    what: 'Kalit so‘z fikrni eslatadi, lekin jumlani tayyorlab bermaydi. Shu sabab nutq tabiiy qoladi.',
    why: 'Matn o‘qish ovozni tekislashtiradi va gapni jonli suhbatdan uzoqlashtiradi.',
    how: ['Har kalit so‘zga bitta kichik bo‘lim ajrating.', 'So‘zga qarab, keyin erkin jumla tuzing.', 'Keyingi bo‘limga pauza bilan o‘ting.'],
    goodExample: '“Tabiat — oila — kitob” so‘zlaridan erkin hikoya tuzish.',
    badExample: 'Kalit so‘z o‘rniga ekranga uzun jumla yozib olish.',
    check: 'Nutq o‘qilgandek emas, suhbatdek eshitildimi?'
  },
  {
    day: 24,
    title: 'Qisqa va batafsil javob',
    skill: 'Bir mazmunni vaqtga moslashtirish',
    durationMinutes: 16,
    recommendedSeconds: 120,
    activeMetricIds: ['mantiq', 'sozTanlash', 'tasir'],
    warmup: '“Nega bu kasbni tanladingiz?” savoliga avval bir, keyin uch jumlada javob bering.',
    prompt: 'Siz o‘rganayotgan muhim ko‘nikmani avval 20 soniyada, keyin 2 daqiqada tushuntiring.',
    keywords: ['Asosiy javob', 'Misol', 'Tafsilot'],
    what: 'Moslashuvchan javobda asosiy mazmun o‘zgarmaydi, faqat tafsilot miqdori o‘zgaradi.',
    why: 'Yig‘ilishda qisqa, suhbatda esa batafsil javob kerak bo‘lishi mumkin.',
    how: ['20 soniyalik javobda fikr va bitta sabab ayting.', 'Uzun javobga misol va tafsilot qo‘shing.', 'Ikkala variantni bir xil xulosa bilan bog‘lang.'],
    goodExample: 'Qisqa variantdagi asosiy jumlani uzun variantning boshida ham saqlash.',
    badExample: 'Uzun javobda butunlay boshqa pozitsiyaga o‘tib ketish.',
    check: 'Ikkala javobning asosiy xulosasi bir xilmi?'
  },
  {
    day: 25,
    title: 'Ovozni xolis eshitish',
    skill: 'Mazmundan alohida ovoz va ohangni tahlil qilish',
    durationMinutes: 14,
    recommendedSeconds: 90,
    activeMetricIds: ['talaffuz', 'ovoz', 'qatiyat'],
    warmup: 'Bir jumlani yozib, ko‘zingizni yumgan holda faqat ohang va tezlikni eshiting.',
    prompt: 'Sizni ilhomlantiradigan bir inson yoki g‘oya haqida gapiring.',
    keywords: ['Kim yoki nima', 'Sabab', 'Ta’siri'],
    what: 'Bugun yozuvni avval mazmunga emas, faqat ovozga e’tibor berib eshitasiz.',
    why: 'Mazmun kuchli bo‘lsa, talaffuz va ohangdagi kamchiliklar ko‘zdan qochishi mumkin.',
    how: ['Birinchi tinglashda tezlikni kuzating.', 'Ikkinchisida talaffuz va so‘z oxirlarini eshiting.', 'Uchinchisida urg‘u va intonatsiyani belgilang.'],
    goodExample: '“00:34 da gap oxiri pasaydi” kabi vaqtli, aniq kuzatuv.',
    badExample: '“Ovozim yomon” kabi dalilsiz umumiy baho.',
    check: 'Kamida bitta vaqtli ovoz kuzatuvi yozdingizmi?'
  },
  {
    day: 26,
    title: 'Uch daqiqalik nutq',
    skill: 'Uzoq nutqda diqqat va tuzilmani saqlash',
    durationMinutes: 20,
    recommendedSeconds: 180,
    activeMetricIds: ['oqim', 'mantiq', 'dalil', 'ovoz', 'tasir'],
    warmup: 'Uch bo‘limli reja tuzing. Har bo‘lim uchun bitta misol tanlang.',
    prompt: 'Texnologiya odatlarimizni qanday o‘zgartiryapti?',
    keywords: ['Oldin', 'Hozir', 'Tavsiya'],
    what: 'Uzoq nutq ko‘proq gapirish emas. Bir asosiy savol atrofida bo‘limlarni izchil ochishdir.',
    why: 'Taqdimot va suhbatda ikki daqiqadan keyin ham tinglovchi yo‘nalishni yo‘qotmasligi kerak.',
    how: ['Kirishda asosiy savolni ayting.', 'Uch bo‘limning har biriga bitta misol bering.', 'Xulosada barcha bo‘limni qayta sanamasdan bitta fikr qoldiring.'],
    goodExample: 'Oldingi odat → hozirgi o‘zgarish → ongli foydalanish tavsiyasi.',
    badExample: 'Bir-biriga aloqasiz ko‘p misol aytish.',
    check: 'Uch daqiqada asosiy yo‘nalish saqlanib qoldimi?'
  },
  {
    day: 27,
    title: 'Intervyu javobi',
    skill: 'Savolga dalilli va ishonchli javob berish',
    durationMinutes: 20,
    recommendedSeconds: 120,
    activeMetricIds: ['mantiq', 'dalil', 'qatiyat', 'tasir'],
    warmup: '“Mening kuchli tomonim...” jumlasini da’vosiz, bitta dalil bilan ayting.',
    prompt: '“Qiyin vaziyatda qanday qaror qilgansiz?” savoliga VHN yoki STAR modeli bilan javob bering.',
    keywords: ['Vaziyat', 'Qaror', 'Natija'],
    what: 'Intervyu javobi savolga to‘g‘ri javob, real vaziyat va sizning hissangizni birlashtiradi.',
    why: 'Umumiy sifatlar emas, kuzatiladigan harakat va natija ishontiradi.',
    how: ['Savolga birinchi jumlada javob bering.', 'Vaziyatni qisqa ayting.', 'Qaroringiz va natijani aniq ko‘rsating.'],
    goodExample: '“Men avval xavfni ajrataman. Masalan, oxirgi loyihada... Natijada...”',
    badExample: 'O‘zingizni haddan ortiq maqtash yoki jamoaning ishini o‘zingizga olish.',
    check: 'Javobdan siz qanday qaror qilishingiz bilinadimi?'
  },
  {
    day: 28,
    title: 'To‘liq 4/3/2',
    skill: 'Takror orqali ravonlik va ixchamlikni oshirish',
    durationMinutes: 25,
    recommendedSeconds: 180,
    activeMetricIds: ['oqim', 'tezlik', 'mantiq', 'talaffuz', 'tasir'],
    warmup: 'Mavzuning bir jumlalik xulosasi va uch tayanch nuqtasini yozing.',
    prompt: 'Sizningcha, kelajakda ta’lim qanday bo‘lishi kerak?',
    keywords: ['Muammo', 'Kelajak', 'Taklif'],
    what: 'Bugun bir mavzuni uzun va qisqa variantda aytasiz. Ilovadagi ikki urinish 3 va 2 daqiqalik variant bo‘ladi.',
    why: 'Bir xil mazmunni takrorlash so‘z izlashni kamaytiradi va asosiy fikrni kuchaytiradi.',
    how: ['Birinchi urinishda uch daqiqa gapiring.', 'Takror va ortiqcha kirishni belgilang.', 'Ikkinchi urinishni ikki daqiqaga ixchamlashtiring.'],
    goodExample: 'Ikkinchi variantda dalil saqlanadi, faqat takror va ortiqcha izoh kamayadi.',
    badExample: 'Qisqartirish uchun talaffuzni buzadigan darajada tez gapirish.',
    check: 'Ikkinchi urinish qisqaroq va ravonroq bo‘ldimi?'
  },
  {
    day: 29,
    title: 'Eng qiyin mashq',
    skill: 'Shaxsiy zaiflikka maqsadli ishlash',
    durationMinutes: 18,
    recommendedSeconds: 120,
    activeMetricIds: ['oqim', 'parazit', 'mantiq', 'talaffuz', 'qatiyat'],
    warmup: 'Progress sahifasidan eng past ko‘rsatkichni tanlang va unga bitta aniq fokus yozing.',
    prompt: '30 kun davomida sizga eng qiyin bo‘lgan nutq ko‘nikmasi va uni qanday mashq qilganingizni ayting.',
    keywords: ['Qiyinchilik', 'Mashq', 'O‘zgarish'],
    what: 'Bugun umumiy ball emas, siz tanlagan eng qiyin bitta ko‘nikma asosiy mezon bo‘ladi.',
    why: 'Maqsadli mashq zaiflikni yashirmaydi; uni kichik va o‘lchanadigan vazifaga aylantiradi.',
    how: ['Oldingi dalildan zaiflikni tanlang.', 'Ikkinchi urinish uchun bitta fokus belgilang.', 'Faqat shu fokusdagi o‘zgarishni solishtiring.'],
    goodExample: '“14-kunda xulosa yo‘q edi; bugun oxirgi jumlani oldindan belgilayman.”',
    badExample: '“Hammasini yaxshilayman” kabi o‘lchanmaydigan maqsad.',
    check: 'Tanlangan bitta zaiflikda farq eshitildimi?'
  },
  {
    day: 30,
    title: 'Yakuniy sinov',
    skill: '1-kun bilan bir xil sharoitda natijani ko‘rish',
    durationMinutes: 25,
    recommendedSeconds: 60,
    activeMetricIds: Object.keys(METRICS),
    warmup: '1-kundagidek joy va mikrofon masofasini tanlang. Faqat uch tayanch so‘zni yozing.',
    prompt: 'O‘zingizni tanishtiring: nima bilan shug‘ullanasiz, nimaga qiziqasiz va nutqingizda nimani yaxshiladingiz?',
    keywords: ['Men haqimda', 'Qiziqishim', 'Natijam'],
    what: 'Yakuniy sinov 1-kundagi vazifani deyarli bir xil sharoitda takrorlaydi.',
    why: 'Eng ishonchli natija — sizning ikki real yozuvingiz, dalillaringiz va bir xil mezonlardagi farq.',
    how: ['1-kun yozuvini avval eshitmang; tabiiy yakuniy yozuv qiling.', 'Ikki urinish bilan bugungi eng yaxshi variantni yarating.', 'So‘ng 1-kun va 30-kunni solishtiring.'],
    goodExample: 'Ball bilan birga parazitlar, pauza, tuzilma va o‘zingiz sezgan farqni yozish.',
    badExample: 'Faqat umumiy ballga qarab, real audio farqni e’tiborsiz qoldirish.',
    check: '30 kunlik eng muhim uchta o‘zgarishni dalil bilan ayta olasizmi?'
  }
];

function stageForDay(day) {
  return STAGES.find(stage => day >= stage.from && day <= stage.to);
}

const CURRICULUM = DAYS.map(item => {
  const stage = stageForDay(item.day);
  const narrationText = [
    `${item.day}-kun. ${item.title}.`,
    item.what,
    item.why,
    'Bajarish tartibi:',
    ...item.how.map((step, index) => `${index + 1}. ${step}`),
    `Yaxshi misol: ${item.goodExample}`,
    `Ehtiyot bo‘ling: ${item.badExample}`,
    `Bugungi topshiriq: ${item.prompt}`,
    `Tekshiruv savoli: ${item.check}`
  ].join(' ');

  return {
    ...item,
    stageId: stage.id,
    stageName: stage.title,
    mediaMode: 'audio',
    focusOptions: COMMON_FOCUS,
    narrationText,
    activeMetrics: item.activeMetricIds.map(id => METRICS[id])
  };
});

function getDay(day) {
  return CURRICULUM.find(item => item.day === Number(day)) || null;
}

module.exports = {
  COMMON_FOCUS,
  CURRICULUM,
  METRICS,
  PILLARS,
  STAGES,
  getDay
};

