// Short, focused drills. Each has an observable check and a transfer task.
const DRILLS = [
  { id: 'silent-pause', pillar: 'ravonlik', title: 'Parazit o‘rniga pauza', minutes: 3, unlockDay: 1, prompt: 'Bugun qilgan foydali ishingizni uch jumlada tushuntiring.', method: 'Har yangi fikrdan oldin labni yoping, sokin nafas oling, keyin davom eting.', example: '“Bugun reja tuzdim. [sukut] Avval eng muhim ishni tugatdim.”', check: '60 soniyada “eee”, “haligi” va shunga o‘xshash to‘ldiruvchilarni sanang. Ikkinchi aytishda bittaga kamaytiring.', transfer: 'Keyingi suhbatda javobdan oldin bir marta jim pauza qiling.' },
  { id: 'one-breath', pillar: 'ravonlik', title: 'Bir nafas, bir fikr', minutes: 3, unlockDay: 2, prompt: 'Ish kuningizni uch asosiy qadamda ayting.', method: 'Har tugallangan jumladan keyin nafas oling. So‘z oxirini yutmang.', example: '“Ertalab rejani ko‘raman. [nafas] Keyin asosiy vazifani bajaraman.”', check: 'Har uch jumlaning oxirgi so‘zi ravshan eshitildimi?', transfer: 'Yig‘ilishda birinchi fikringizni qisqa jumla bilan tugating.' },
  { id: 'pace-shift', pillar: 'ravonlik', title: 'Tezlikni boshqarish', minutes: 4, unlockDay: 4, prompt: 'Sevimli odatingizning foydasini ayting.', method: 'Bir xil fikrni avval shoshilmasdan, keyin odatiy tezlikda ayting. Muhim so‘z oldida pauza qiling.', example: '“Asosiy foyda — [pauza] vaqtni tejash.”', check: 'Ikkinchi aytishda ham so‘z oxiri va asosiy fikr aniq qoldimi?', transfer: 'Muhim raqam yoki qarorni aytishdan oldin tezlikni pasaytiring.' },
  { id: 'concrete-detail', pillar: 'aniqlik', title: 'Umumiy so‘zni aniqlashtirish', minutes: 4, unlockDay: 5, prompt: 'Siz ko‘p ishlatadigan ilovani tavsiya qiling.', method: '“Yaxshi”, “qulay”, “zo‘r” o‘rniga bitta kuzatiladigan xususiyat va foyda ayting.', example: '“Qulay” o‘rniga “uch bosishda hujjatni topaman”.', check: 'Tinglovchi aynan qaysi xususiyat foyda berishini bila oladimi?', transfer: 'Bugun bir tavsiyangizda aniq raqam yoki holat qo‘shing.' },
  { id: 'filler-audit', pillar: 'aniqlik', title: 'Parazitlar auditi', minutes: 4, unlockDay: 4, prompt: 'Bir ishni qanday o‘rganganingizni 60 soniyada ayting.', method: 'Birinchi aytishda to‘ldiruvchi so‘zlarni sanang. Ikkinchisida kelayotganini sezsangiz jim turing.', example: '“Xullas, demak...” o‘rniga bir soniya sukut.', check: 'Birinchi va ikkinchi urinishdagi parazitlar sonini solishtiring.', transfer: 'Keyingi qo‘ng‘iroqda bitta tez-tez ishlatadigan parazitingizni kuzating.' },
  { id: 'plain-language', pillar: 'aniqlik', title: 'Jargonsiz tushuntirish', minutes: 5, unlockDay: 8, prompt: 'O‘z kasbingizdagi bir atamani yangi boshlovchiga tushuntiring.', method: 'Avval oddiy ta’rif, keyin kundalik misol, oxirida atamani ayting.', example: '“Ma’lumot zaxirasi — faylning ikkinchi nusxasi.”', check: 'Izohni atamani bilmagan odam ham tushunadimi?', transfer: 'Real suhbatda bitta murakkab so‘zni sodda izoh bilan almashtiring.' },
  { id: 'prep-answer', pillar: 'tuzilma', title: 'Fikr–sabab–misol–xulosa', minutes: 5, unlockDay: 6, prompt: 'Masofadan ishlash qachon foydali?', method: 'Birinchi jumlada javob, keyin bitta sabab, hayotiy misol va yakun bering.', example: '“Men uchun foydali. Yo‘lga vaqt ketmaydi. Masalan... Shuning uchun...”', check: 'To‘rt qismning har biri eshitildimi, xulosa savolga qaytdimi?', transfer: 'Keyingi fikr bildirishingizda bitta misol keltiring.' },
  { id: 'thirty-second-brief', pillar: 'tuzilma', title: '30 soniyalik xabar', minutes: 4, unlockDay: 10, prompt: 'Jamoaga bir ishning holatini yetkazing.', method: 'Holatni bir jumlada ayting, to‘siqni nomlang, keyingi qadam va muddatni ko‘rsating.', example: '“Loyiha tayyor. Faqat tasdiq qolgan. Bugun soat beshgacha yuboraman.”', check: 'Kim nima va qachon qilishini eshitish mumkinmi?', transfer: 'Ishdagi bitta xabarni shu tartibda bering.' },
  { id: 'star-story', pillar: 'tuzilma', title: 'Vaziyat–harakat–natija', minutes: 5, unlockDay: 11, prompt: 'Bir muammoni hal qilganingizni ayting.', method: 'Vaziyatga 20%, o‘zingiz qilgan harakatga 50%, natijaga 30% vaqt ajrating.', example: '“Muddat qisqa edi. Men ishni bo‘ldim. Natijada bir kun oldin tugatdik.”', check: 'Shaxsiy hissangiz va natija aniq ko‘rindimi?', transfer: 'Intervyu yoki tanishuvda bitta real voqeani shu qolipda ayting.' },
  { id: 'ending-sounds', pillar: 'yetkazish', title: 'So‘z oxirini ochish', minutes: 3, unlockDay: 3, prompt: '“Tartib ishni tezlashtiradi” jumlasini uch tezlikda ayting.', method: 'Avval sekin ayting; har bir oxirgi undoshni eshiting. Keyin tabiiy tezlikka qayting.', example: '“Tezlashtiradi” so‘zining oxirgi bo‘g‘inini yutmang.', check: 'Telefon yozuvida barcha so‘zlarni taxminsiz ajrata oldingizmi?', transfer: 'Bugun bitta muhim gapning so‘nggi so‘zini ravshan tugating.' },
  { id: 'stress-keyword', pillar: 'yetkazish', title: 'Kalit so‘zga urg‘u', minutes: 4, unlockDay: 16, prompt: 'Taklifingizning eng muhim foydasini ayting.', method: 'Bir jumladagi faqat bitta muhim so‘zni belgilang. Uning oldida pauza va yengil urg‘u qiling.', example: '“Bu usul [pauza] vaqtni tejaydi.”', check: 'Tinglagan odam asosiy so‘zni darhol topa oladimi?', transfer: 'Keyingi taqdimotda bitta asosiy raqamga urg‘u bering.' },
  { id: 'audible-ending', pillar: 'yetkazish', title: 'Jumla oxirini saqlash', minutes: 3, unlockDay: 2, prompt: 'Bir taklifni uchta qisqa jumlada ayting.', method: 'Jumla boshidagi balandlikni zo‘riqmasdan oxirigacha saqlang; oxirida nafasni tugatib yubormang.', example: '“Ertaga boshlaymiz” jumlasida “boshlaymiz” ham ravshan bo‘lsin.', check: 'Yozuvda oxirgi so‘zlar ham boshidagi kabi eshitildimi?', transfer: 'Qo‘ng‘iroqda xulosani ravshan tugating.' },
  { id: 'first-sentence', pillar: 'ishonch', title: 'Birinchi jumlada javob', minutes: 4, unlockDay: 6, prompt: 'Nega aynan siz bu vazifaga mossiz?', method: 'Savolni takrorlamang. Bitta aniq javob ayting, keyin qisqa dalil keltiring.', example: '“Men mosman, chunki shunga o‘xshash ikki loyihani tugatganman.”', check: 'Asosiy javob birinchi 10 soniyada eshitildimi?', transfer: 'Keyingi savolga javobni kirishsiz boshlang.' },
  { id: 'respectful-no', pillar: 'ishonch', title: 'Muloyim rad javobi', minutes: 5, unlockDay: 23, prompt: 'Bugun qo‘shimcha vazifani ola olmasligingizni ayting.', method: 'Chegarani aniq ayting, qisqa sabab bering, iloji bo‘lsa muqobil taklif qiling.', example: '“Bugun ulgurmayman. Ertaga soat o‘nda ko‘ra olaman.”', check: 'Rad javobi aniqmi va ortiqcha uzr bilan cho‘zilmadimi?', transfer: 'Real vaziyatda chegarangizni bitta to‘liq jumlada ayting.' },
  { id: 'objection-response', pillar: 'ishonch', title: 'E’tirozga javob', minutes: 5, unlockDay: 24, prompt: '“Bu reja juda qimmat” e’tiroziga javob bering.', method: 'Avval e’tirozni qayta ifodalang, keyin bitta dalil va bitta tanlov taklif qiling.', example: '“Narx muhimligini tushundim. Tejaladigan vaqtni hisoblaylik.”', check: 'Javob himoyalanishsiz, savolga mos va dalillimi?', transfer: 'Bahsda javobdan oldin qarshi fikrni bir jumlada qayta ayting.' }
];

function getDrill(id) { return DRILLS.find(item => item.id === id) || null; }

module.exports = { DRILLS, getDrill };
